# Generated by Django 4.2.6 on 2023-10-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employee_age_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.IntegerField(max_length=0)),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductPrice', models.IntegerField(max_length=0)),
                ('Description', models.CharField(max_length=300)),
            ],
        ),
    ]
