# Generated by Django 4.2.6 on 2023-11-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductPrice',
            field=models.IntegerField(default=0),
        ),
    ]
