# Generated by Django 4.2.6 on 2023-11-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.IntegerField(default=0),
        ),
    ]
